version: '2.6.1'

x-shared: &shared
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_USER=changeUser
    - DB_POSTGRESDB_PASSWORD=changePassword
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - NODE_FUNCTION_ALLOW_BUILTIN=*
    - NODE_FUNCTION_ALLOW_EXTERNAL=axios,cheerio,express,firebase-admin,firebase-functions,firebase-tools,fs,googleapis,https,http,mysql,mysql2,pg,pg-hstore,redis,sequelize,sequelize-cli,sharp,sqlite3,uuid,vue
  links:
    - postgres
    - redis
  volumes:
    - n8n_storage:/home/node/.n8n
    - n8n_storage:/root/.n8n
    - n8n_files:/files

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=changeUser
      - POSTGRES_PASSWORD=changePassword
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=changeUser
      - POSTGRES_NON_ROOT_PASSWORD=changePassword
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_storage:/data

  n8n:
    <<: *shared
    ports:
      - 5678:5678

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n
