version: '2.6.1'

x-shared: &shared
  restart: always
  build:
    context: ./docker/images/n8n-awsh/vendor/n8n
    dockerfile: Dockerfile
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_USER=changeUser
    - DB_POSTGRESDB_PASSWORD=changePassword
    - NODE_FUNCTION_ALLOW_BUILTIN=*
    - NODE_FUNCTION_ALLOW_EXTERNAL=axios,cheerio,express,firebase-admin,firebase-functions,firebase-tools,fs,googleapis,https,http,mysql,mysql2,pg,pg-hstore,redis,sequelize,sequelize-cli,sharp,sqlite3,uuid,vue,selenium-webdriver
  links:
    - postgres
    - redis
    - selenoid
  volumes:
    - n8n_storage:/home/node/.n8n
    - n8n_storage:/root/.n8n
    - n8n_files:/files

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=changeUser
      - POSTGRES_PASSWORD=changePassword
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=changeUser
      - POSTGRES_NON_ROOT_PASSWORD=changePassword
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_storage:/data

  selenoid:
    build:
      context: ./docker/images/n8n-awsh/vendor/selenoid
      dockerfile: Dockerfile
    networks:
      - selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - selenoid_config:/etc/selenoid/

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    networks:
      - selenoid
    links:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444
    command: [ "--selenoid-uri", "http://selenoid:4444","-container-network","selenoid"]

  selenoid-chrome-setup:
    image: selenoid/chrome:124.0
    command: /bin/true  # This command does nothing and exits immediately
    restart: "no"  # Ensures the container does not restart

  n8n:
    <<: *shared
    ports:
      - 5678:5678

#  n8n-worker:
#    <<: *shared
#    command: worker
#    depends_on:
#      - n8n
